### ISSUE TITLE
Consider changing mime_for_path's parameter type to a generic that impls AsRef<Path>

### ISSUE THREAD

**Issue by ghost** [conduit-rust/conduit-mime-types#5]
This is a minor issue, and one that 

`mime_for_path`'s parameter type is `&Path`. However, having a generic parameter that accepts any type that implements `AsRef<Path>` might be a more favorable.

I do recognize the possibility of the current parameter type being a deliberate decision. I wanted to bring this issue to your attention on the off chance that it wasn't.

**Comment by Turbo87** [comment]
Since the project is no longer being used by crates.io we are deprecating it and will be closing this issue.
