### ISSUE TITLE
Consider specifying min_rust_version

### ISSUE THREAD

**Issue by peacememories** [conduit-rust/conduit-mime-types#9]
I've recently tried to build another crate - iron - with an older version of Rust, because the newest version is not available in my environment. Unfortunately, the build fails because conduit-mime-types uses language features which are unstable in rust 1.15

I think this should be expressed in the minimal rustc version of the crate. I don't know if cargo can handle this incompatibility, but even if it cannot, this would make it easier to add such a feature in the future, and it would make the error message clearer to users ( e.g. "this crate does not support your current version of rust")

Thank you for considering this :)

**Comment by Turbo87** [comment]
Since the project is no longer being used by crates.io we are deprecating it and will be closing this issue.
